import { describe, expect, it } from 'vitest';
import {
  type BoringFilePreset,
  boringFilePresetsFor,
  filterBoringFiles,
  parseBoringFilePresets
} from './boring-files';
import type { DiffFile } from './types';

describe('boring file presets', () => {
  it('classifies lockfiles', () => {
    for (const lockfile of [
      'package-lock.json',
      'pnpm-lock.yaml',
      'yarn.lock',
      'bun.lock',
      'bun.lockb',
      'Cargo.lock',
      'Gemfile.lock',
      'Pipfile.lock',
      'poetry.lock',
      'uv.lock',
      'go.sum',
      'composer.lock',
      'mix.lock',
      'flake.lock',
      'deno.lock',
      'Podfile.lock'
    ]) {
      expect(presets(lockfile), lockfile).toContain('lockfiles');
      expect(presets(`frontend/${lockfile}`), `frontend/${lockfile}`).toContain('lockfiles');
    }
    expect(presets('src/lockfile.ts')).not.toContain('lockfiles');
  });

  it('classifies snapshots', () => {
    expect(presets('src/__snapshots__/button.test.ts.snap')).toContain('snapshots');
    expect(presets('src/view.snapshot.json')).toContain('snapshots');
    expect(presets('src/snapshot-helper.ts')).not.toContain('snapshots');
  });

  it('classifies generated files by path and content markers', () => {
    expect(presets('src/__generated__/schema.ts')).toContain('generated');
    expect(presets('src/generated/schema.ts')).toContain('generated');
    expect(presets('src/schema.generated.ts')).toContain('generated');
    expect(presets('src/service.pb.go')).toContain('generated');
    expect(presets('src/manual.ts', '// Code generated by protoc. DO NOT EDIT.')).toContain(
      'generated'
    );
    expect(presets('src/graphql.ts', '/* @generated */')).toContain('generated');
    expect(presets('src/general.ts')).not.toContain('generated');
    expect(presets('src/constants.ts', "'Code generated',")).not.toContain('generated');
    expect(presets('src/constants.ts', "'@generated',")).not.toContain('generated');
  });

  it('classifies vendored paths', () => {
    expect(presets('vendor/pkg/file.go')).toContain('vendored');
    expect(presets('third_party/lib/index.ts')).toContain('vendored');
    expect(presets('node_modules/pkg/index.js')).toContain('vendored');
    expect(presets('.yarn/cache/pkg.zip')).toContain('vendored');
    expect(presets('frontend/.yarn/cache/pkg.zip')).toContain('vendored');
    expect(presets('src/external-link.ts')).not.toContain('vendored');
  });

  it('filters files by selected presets while preserving order', () => {
    const files = [
      makeFile('src/app.ts'),
      makeFile('pnpm-lock.yaml'),
      makeFile('src/__generated__/types.ts'),
      makeFile('vendor/pkg/index.ts')
    ];
    const result = filterBoringFiles(files, new Set<BoringFilePreset>(['lockfiles', 'vendored']));

    expect(result.files.map((file) => file.path)).toEqual([
      'src/app.ts',
      'src/__generated__/types.ts'
    ]);
    expect(result.hidden.map((file) => file.path)).toEqual([
      'pnpm-lock.yaml',
      'vendor/pkg/index.ts'
    ]);
  });

  it('parses persisted preset ids defensively', () => {
    expect(Array.from(parseBoringFilePresets(['lockfiles', 'unknown', 'generated']))).toEqual([
      'lockfiles',
      'generated'
    ]);
    expect(Array.from(parseBoringFilePresets('lockfiles'))).toEqual([]);
  });
});

function presets(path: string, content = ''): Set<BoringFilePreset> {
  return boringFilePresetsFor(makeFile(path, content));
}

function makeFile(path: string, content = ''): DiffFile {
  return {
    path,
    oldPath: null,
    additions: content ? 1 : 0,
    deletions: 0,
    isBinary: false,
    isDeleted: false,
    isNew: false,
    isRenamed: false,
    language: null,
    hunks: content
      ? [
          {
            oldStart: 1,
            oldLines: 0,
            newStart: 1,
            newLines: 1,
            header: '',
            lines: [{ type: 'add', oldLine: null, newLine: 1, content }]
          }
        ]
      : []
  };
}
